name: 'dbt_project_1_tax'
version: '1.0.0'
config-version: 2
profile: 'dbt_project_1_tax'

models:
  dbt_project_1_tax:
    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: marts
      +materialized: table

seeds:
  dbt_project_1_tax:
      +schema: seeds