dbt_project_1_tax:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbt-project-1-tax
      dataset: tax_admin
      threads: 4
      keyfile: ./bigquery_key.json